import Products from "@/components/home/Products";

export const metadata = {
    title: "All Products",
    description: "Generated by create next app",
};

const ProductsPage = () => {
    return (
        <div>
            <Products />
        </div>
    );
};

export default ProductsPage;